# AI Agents (SAFE VERSION FOR HACKATHON DEMO)

def generate_lesson_plan(text):
    return f"""
📘 LESSON PLAN (45 MIN)

OBJECTIVES:
- Understand key concepts from the uploaded chapter
- Build foundational understanding step by step

EXPLANATION:
This content is simplified from your document:

{text[:500]}...

TEACHING FLOW:
1. Introduction to topic
2. Core explanation with examples
3. Quick recap
4. Student interaction activity

NOTE:
This is generated by TeachFlow AI multi-agent system.
"""


def generate_quiz(text):
    return f"""
🧪 QUIZ SECTION

MCQs:

1. What is the main idea of the chapter?
A) Option A
B) Option B
C) Option C
D) Option D

Answer: C

2. Which concept is important here?
A) Concept 1
B) Concept 2
C) Concept 3
D) Concept 4

Answer: B

SHORT QUESTIONS:
1. Explain the topic in your own words.
2. Write one real-life application.

Source Preview:
{text[:300]}...
"""